name: CI

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run dist
      - name: extract artifacts
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: dist/*.dmg